name: Build Minecraft Plugin

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      # Força o Maven a usar o pom.xml que está exatamente na raiz principal
      run: mvn -B package -f ./pom.xml

    - name: Upload Plugin JAR
      uses: actions/upload-artifact@v4
      with:
        name: SurvivalMinigames-Jar
        path: target/*.jar
